# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tendenciass.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtChart import QChart, QChartView, QValueAxis, QBarCategoryAxis, QBarSet, QBarSeries
from PyQt5.Qt import Qt

class Ui_Dialog8(object):
    def setupUi(self, Dialog,dictionary,weight,printers):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 700)

        values=list(dictionary.values())
        keyss=list(dictionary.keys())


        set0 = QBarSet('Material Consumido')
        set0.append(values)
        series = QBarSeries()
        series.append(set0)
        chart = QChart()
        chart.addSeries(series)

        chart.setAnimationOptions(QChart.SeriesAnimations)
        material = tuple(dictionary.keys())

        axisX = QBarCategoryAxis()
        axisX.append(material)

        axisY = QValueAxis()
        max_value=max(dictionary.values())
        axisY.setRange(0, max_value)

        chart.addAxis(axisX,Qt.AlignBottom)
        chart.addAxis(axisY,Qt.AlignLeft)

        chart.legend().setVisible(True)
        chart.legend().setAlignment(Qt.AlignBottom)

        self.chartView = QChartView(chart)


        
        Dialog.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(25)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(25)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.peso_prom = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(17)
        self.peso_prom.setFont(font)
        self.peso_prom.setText(str(weight))
        self.peso_prom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.peso_prom.setObjectName("peso_prom")
        self.verticalLayout.addWidget(self.peso_prom)
        self.n_impresiones = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(17)
        self.n_impresiones.setFont(font)
        
        self.n_impresiones.setText(str(printers))
        self.n_impresiones.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.n_impresiones.setObjectName("n_impresiones")
        self.verticalLayout.addWidget(self.n_impresiones)
        self.used_material = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(17)
        self.used_material.setFont(font)
        self.used_material.setText(keyss[values.index(max_value)])
        self.used_material.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.used_material.setObjectName("used_material")
        self.verticalLayout.addWidget(self.used_material)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.chartView)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(39, 39, 39);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Análisis de Tendencia"))
        self.label_2.setText(_translate("Dialog", "Peso Promedio:"))
        self.label_3.setText(_translate("Dialog", "Total Impresiones:"))
        self.label_4.setText(_translate("Dialog", "Material Más Usado:"))



