# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updates.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
"MainWindow"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1357, 920)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.setWindowIcon(QtGui.QIcon('logo.jpg'))
        MainWindow.setFont(font)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("background-color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_search = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setItalic(True)
        self.line_search.setFont(font)
        self.line_search.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.line_search.setObjectName("line_search")
        self.horizontalLayout_2.addWidget(self.line_search)
        self.button_search = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_search.setFont(font)
        self.button_search.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(255, 255, 255);")
        self.button_search.setObjectName("button_search")
        self.horizontalLayout_2.addWidget(self.button_search)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_date_search = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_date_search.setFont(font)
        self.button_date_search.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 185, 88);")
        self.button_date_search.setObjectName("button_date_search")
        self.horizontalLayout_3.addWidget(self.button_date_search)


        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cot_lista = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setItalic(True)
        self.cot_lista.setFont(font)
        self.cot_lista.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cot_lista.setObjectName("cot_lista")
        self.verticalLayout_2.addWidget(self.cot_lista)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_cot = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_cot.setFont(font)
        self.button_cot.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(255, 255, 255);")
        self.button_cot.setObjectName("button_cot")
        self.verticalLayout.addWidget(self.button_cot)
        self.button_tend_servicios = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_tend_servicios.setFont(font)
        self.button_tend_servicios.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(255, 255, 255);")
        self.button_tend_servicios.setObjectName("button_tend_servicios")
        self.verticalLayout.addWidget(self.button_tend_servicios)
        self.button_past_service = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_past_service.setFont(font)
        self.button_past_service.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(255, 255, 255);")
        self.button_past_service.setObjectName("button_past_service")
        self.verticalLayout.addWidget(self.button_past_service)
        self.eliminar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.eliminar.setFont(font)
        self.eliminar.setStyleSheet("background-color: rgb(220, 185, 88);\n"
"color: rgb(255, 255, 255);")
        self.eliminar.setObjectName("eliminar")
        self.verticalLayout.addWidget(self.eliminar)
        self.button_mens_consume = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Futura Bk BT")
        font.setPointSize(12)
        font.setItalic(True)
        self.button_mens_consume.setFont(font)
        self.button_mens_consume.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(220, 185, 88);")
        self.button_mens_consume.setObjectName("button_mens_consume")
        self.verticalLayout.addWidget(self.button_mens_consume)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1357, 21))
        self.menubar.setObjectName("menubar")
        self.menuconfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuconfiguracion.setObjectName("menuconfiguracion")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionimpresora = QtWidgets.QAction(MainWindow)
        self.actionimpresora.setObjectName("actionimpresora")
        self.actionmaterial = QtWidgets.QAction(MainWindow)
        self.actionmaterial.setObjectName("actionmaterial")
        self.actionGeneral = QtWidgets.QAction(MainWindow)
        self.actionGeneral.setObjectName("actionGeneral")
        self.actionmaterial_2 = QtWidgets.QAction(MainWindow)
        self.actionmaterial_2.setObjectName("actionmaterial_2")
        self.menuconfiguracion.addSeparator()
        self.menuconfiguracion.addAction(self.actionimpresora)
        self.menuconfiguracion.addAction(self.actionGeneral)
        self.menuconfiguracion.addAction(self.actionmaterial_2)
        self.menubar.addAction(self.menuconfiguracion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D Printing Calculator"))
        self.label.setText(_translate("MainWindow", "Cotizaciones"))
        self.button_search.setText(_translate("MainWindow", "Buscar"))
        self.button_date_search.setText(_translate("MainWindow", "Buscar por fecha:"))

        self.button_cot.setText(_translate("MainWindow", "Cotizar"))
        self.button_tend_servicios.setText(_translate("MainWindow", "Analisis De Tendencia En Los Servicios"))
        self.button_past_service.setText(_translate("MainWindow", "Abrir Cotización"))
        self.eliminar.setText(_translate("MainWindow", "Eliminar Cotización"))
        self.button_mens_consume.setText(_translate("MainWindow", "Análisis Mensual De Consumo"))
        self.menuconfiguracion.setTitle(_translate("MainWindow", "Configuración"))
        self.actionimpresora.setText(_translate("MainWindow", "Impresora"))
        self.actionmaterial.setText(_translate("MainWindow", "Materiales"))
        self.actionGeneral.setText(_translate("MainWindow", "General"))
        self.actionmaterial_2.setText(_translate("MainWindow", "Material"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
