# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cotiz_format.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 693)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.button_save_cotiz = QtWidgets.QDialogButtonBox(Dialog)
        self.button_save_cotiz.setOrientation(QtCore.Qt.Horizontal)
        self.button_save_cotiz.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.button_save_cotiz.setObjectName("button_save_cotiz")
        self.gridLayout.addWidget(self.button_save_cotiz, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -216, 761, 850))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.client_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.client_name.setObjectName("client_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.client_name)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.date_client = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.date_client.setObjectName("date_client")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.date_client)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.description = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.description.setObjectName("description")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.description)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.printer = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.printer.setObjectName("printer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.printer)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.filament = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.filament.setObjectName("filament")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filament)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.weight = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.weight.setObjectName("weight")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.weight)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.printer_time = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.printer_time.setObjectName("printer_time")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.printer_time)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.removal_piece = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.removal_piece.setObjectName("removal_piece")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.removal_piece)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.removal_support = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.removal_support.setObjectName("removal_support")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.removal_support)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.aditional_work = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.aditional_work.setObjectName("aditional_work")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.aditional_work)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.button_model_cad = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_model_cad.setFont(font)
        self.button_model_cad.setObjectName("button_model_cad")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.button_model_cad)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.s_licing = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.s_licing.setObjectName("s_licing")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s_licing)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.material_change = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.material_change.setObjectName("material_change")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.material_change)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.transfer_star = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.transfer_star.setObjectName("transfer_star")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.transfer_star)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.time_pre = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.time_pre.setObjectName("time_pre")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.time_pre)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.cob_ganancia = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.cob_ganancia.setObjectName("cob_ganancia")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cob_ganancia)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.consumibles = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.consumibles.setObjectName("consumibles")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.consumibles)
        self.verticalLayout_6.addLayout(self.formLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.dates_printer=None
        self.button_save_cotiz.clicked.connect(self.save_dates)
        self.retranslateUi(Dialog)
        self.button_save_cotiz.accepted.connect(Dialog.accept)
        self.button_save_cotiz.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def save_dates(self):
        try:
            self.dates_printer=[self.client_name.text(),self.date_client.text(),self.description.toPlainText(),self.printer.text(),self.filament.text(),float(self.weight.text()),
                                float(self.printer_time.text()),float(self.s_licing.text()),float(self.material_change.text()),float(self.transfer_star.text()),
                                float(self.removal_piece.text()),float(self.removal_support.text()),float(self.aditional_work.text()),
                                float(self.consumibles.text()),float(self.cob_ganancia.text()),float(self.lineEdit.text()),float(self.time_pre.text())]
        except ValueError:
            print("se presento un error al convertir en format cotiz")


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_15.setText(_translate("Dialog", "Datos cliente"))
        self.label.setText(_translate("Dialog", "Nombre:"))
        self.label_2.setText(_translate("Dialog", "Fecha:"))
        self.date_client.setPlaceholderText(_translate("Dialog", "dd/mm/year example:02/12/2020"))
        self.label_3.setText(_translate("Dialog", "Descripción:"))
        self.label_16.setText(_translate("Dialog", "Impresión"))
        self.label_4.setText(_translate("Dialog", "Impresora:"))
        self.label_5.setText(_translate("Dialog", "Filamento:"))
        self.label_6.setText(_translate("Dialog", "Peso:"))
        self.weight.setPlaceholderText(_translate("Dialog", "gramos"))
        self.label_10.setText(_translate("Dialog", "Tiempo impresión:"))
        self.printer_time.setPlaceholderText(_translate("Dialog", "Horas"))
        self.label_18.setText(_translate("Dialog", "Post--processing"))
        self.label_7.setText(_translate("Dialog", "Remoción de la pieza:"))
        self.label_8.setText(_translate("Dialog", "Remoción de soportes:"))
        self.label_9.setText(_translate("Dialog", "Trabajo adicional:"))
        self.label_22.setText(_translate("Dialog", "Tiempo:"))
        self.label_17.setText(_translate("Dialog", "Preparación"))
        self.label_11.setText(_translate("Dialog", "Modelo CAD:"))
        self.button_model_cad.setText(_translate("Dialog", "importar"))
        self.label_12.setText(_translate("Dialog", "Slicing:"))
        self.label_13.setText(_translate("Dialog", "Cambio de material:"))
        self.label_14.setText(_translate("Dialog", "Transferencia y arranque:"))
        self.label_23.setText(_translate("Dialog", "Tiempo:"))
        self.label_19.setText(_translate("Dialog", "Cobro"))
        self.label_20.setText(_translate("Dialog", "Ganancia:"))
        self.label_21.setText(_translate("Dialog", "Consumibles:"))
        self.removal_piece.setPlaceholderText(_translate("Dialog", "minutos"))
        self.removal_support.setPlaceholderText(_translate("Dialog", "minutos"))
        self.aditional_work.setPlaceholderText(_translate("Dialog", "minutos"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "minutos"))
        self.s_licing.setPlaceholderText(_translate("Dialog", "minutos"))
        self.material_change.setPlaceholderText(_translate("Dialog", "minutos"))
        self.transfer_star.setPlaceholderText(_translate("Dialog", "minutos"))
        self.time_pre.setPlaceholderText(_translate("Dialog", "minutos"))
        self.cob_ganancia.setPlaceholderText(_translate("Dialog", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
